In [13]:
import numpy as np
import pandas as pd

In [14]:
np.random.seed(55)

Creating a random sample data

In [15]:
data = {
        "ID": np.arange (1,11),
        "Category": np.random.choice(['A','B','C'], size=10),
        "Value1": np.random.randint(10,100, size=10),
        "Value2": np.random.uniform(1.0,50.0, size=10)
}
df = np.random.randint(10,101)
df = pd.DataFrame(data)
print("Initial DataFrame:\n")
df

Initial DataFrame:

   ID Category  Value1     Value2
0   1        B      45  45.030700
1   2        C      56  49.294968
2   3        A      71  25.340501
3   4        B      87  18.263627
4   5        B      22  43.487165
5   6        B      34  20.447206
6   7        B      81  32.539204
7   8        B      41   2.002212
8   9        B      82  40.596143
9  10        C      61  22.051052

In [16]:
df['Sum'] = np.add(df['Value1'], df['Value2']) # Value1 + Value2
df['Difference'] = np.subtract(df['Value1'], df['Value2']) # Value1 - Value2
df['Product'] = np.multiply(df['Value1'], df['Value2']) # Value1 * Value2
df['Quotient'] = np.divide(df['Value1'], df['Value2']) # Value1 / Value2
df['Floor_div'] = np.floor_divide(df['Value1'], df['Value2']) # Value1 // Value2
df['Mod'] = np.remainder(df['Value1'], 2) # Value1 % 2
df['V1**2'] = np.power(df['Value1'], 2) # Value1 ** 2
df['SquareRoot_V1'] = np.sqrt(df['Value1']) # sqrt of Value1
df['mean_V1'] = np.mean(df['Value1']) # mean of Value1
df['Std_V2'] = np.std(df['Value2']) # Standard Deviation of Value1
print('After Numpy Operations:\n')
df

After Numpy Operations:

,ID,Category,Value1,Value2,Sum,Difference,Product,Quotient,Floor_div,Mod,V1**2,SquareRoot_V1,mean_V1,Std_V2
0,1,B,45,45.030700,90.030700,-0.030700,2026.381519,0.999318,0.0,1,2025,6.708204,58.0,14.129857
1,2,C,56,49.294968,105.294968,6.705032,2760.518180,1.136019,1.0,0,3136,7.483315,58.0,14.129857
2,3,A,71,25.340501,96.340501,45.659499,1799.175585,2.801839,2.0,1,5041,8.426150,58.0,14.129857
3,4,B,87,18.263627,105.263627,68.736373,1588.935581,4.763566,4.0,1,7569,9.327379,58.0,14.129857
4,5,B,22,43.487165,65.487165,-21.487165,956.717624,0.505896,0.0,0,484,4.690416,58.0,14.129857
5,6,B,34,20.447206,54.447206,13.552794,695.204988,1.662819,1.0,0,1156,5.830952,58.0,14.129857
6,7,B,81,32.539204,113.539204,48.460796,2635.675503,2.489305,2.0,1,6561,9.000000,58.0,14.129857
7,8,B,41,2.002212,43.002212,38.997788,82.090706,20.477349,20.0,1,1681,6.403124,58.0,14.129857
8,9,B,82,40.596143,122.596143,41.403857,3328.883694,2.019896,2.0,0,6724,9.055385,58.0,14.129857
9,10,C,61,22.051052,83.051052,38.948948,1345.114160,2.766308,2.0,1,3721,7.810250,58.0,14.129857

In [17]:
filtered_df = df[(df['Value1']>50) & (df['Category']=='B')] # Filtering DataFrame

print('Filtered DataFrame (Value1>50 7 Category == A): \n')
filtered_df

Filtered DataFrame (Value1>50 7 Category == A):

,ID,Category,Value1,Value2,Sum,Difference,Product,Quotient,Floor_div,Mod,V1**2,SquareRoot_V1,mean_V1,Std_V2
3,4,B,87,18.263627,105.263627,68.736373,1588.935581,4.763566,4.0,1,7569,9.327379,58.0,14.129857
6,7,B,81,32.539204,113.539204,48.460796,2635.675503,2.489305,2.0,1,6561,9.000000,58.0,14.129857
8,9,B,82,40.596143,122.596143,41.403857,3328.883694,2.019896,2.0,0,6724,9.055385,58.0,14.129857

In [18]:
grouped = df.groupby('Category').agg({ # grouping and aggregating
    'Value1': ['mean','max','min'],
    'Value2': ['mean', 'sum']
})

print('Grouped and aggregated data: \n')
grouped

Grouped and aggregated data:

         Value1             Value2
           mean max min       mean         sum
Category
A          71.0  71  71  25.340501   25.340501
B          56.0  87  22  28.909465  202.366257
C          58.5  61  56  35.673010   71.346019

In [19]:
df["Value1_Normalized"] = df["Value1"].apply(lambda x: (x - np.min(df["Value1"])) / (np.max(df["Value1"]) - np.min(df["Value1"])))

print("With normalized Value1:\n")
df

With normalized Value1:

,ID,Category,Value1,Value2,Sum,Difference,Product,Quotient,Floor_div,Mod,V1**2,SquareRoot_V1,mean_V1,Std_V2,Value1_Normalized
0,1,B,45,45.030700,90.030700,-0.030700,2026.381519,0.999318,0.0,1,2025,6.708204,58.0,14.129857,0.353846
1,2,C,56,49.294968,105.294968,6.705032,2760.518180,1.136019,1.0,0,3136,7.483315,58.0,14.129857,0.523077
2,3,A,71,25.340501,96.340501,45.659499,1799.175585,2.801839,2.0,1,5041,8.426150,58.0,14.129857,0.753846
3,4,B,87,18.263627,105.263627,68.736373,1588.935581,4.763566,4.0,1,7569,9.327379,58.0,14.129857,1.000000
4,5,B,22,43.487165,65.487165,-21.487165,956.717624,0.505896,0.0,0,484,4.690416,58.0,14.129857,0.000000
5,6,B,34,20.447206,54.447206,13.552794,695.204988,1.662819,1.0,0,1156,5.830952,58.0,14.129857,0.184615
6,7,B,81,32.539204,113.539204,48.460796,2635.675503,2.489305,2.0,1,6561,9.000000,58.0,14.129857,0.907692
7,8,B,41,2.002212,43.002212,38.997788,82.090706,20.477349,20.0,1,1681,6.403124,58.0,14.129857,0.292308
8,9,B,82,40.596143,122.596143,41.403857,3328.883694,2.019896,2.0,0,6724,9.055385,58.0,14.129857,0.923077
9,10,C,61,22.051052,83.051052,38.948948,1345.114160,2.766308,2.0,1,3721,7.810250,58.0,14.129857,0.600000

In [20]:
df.loc[2,'Value1'] = np.nan
df.loc[5,'Value2'] = np.nan

print('With NaN values:\n')
df

With NaN values:

,ID,Category,Value1,Value2,Sum,Difference,Product,Quotient,Floor_div,Mod,V1**2,SquareRoot_V1,mean_V1,Std_V2,Value1_Normalized
0,1,B,45.0,45.030700,90.030700,-0.030700,2026.381519,0.999318,0.0,1,2025,6.708204,58.0,14.129857,0.353846
1,2,C,56.0,49.294968,105.294968,6.705032,2760.518180,1.136019,1.0,0,3136,7.483315,58.0,14.129857,0.523077
2,3,A,NaN,25.340501,96.340501,45.659499,1799.175585,2.801839,2.0,1,5041,8.426150,58.0,14.129857,0.753846
3,4,B,87.0,18.263627,105.263627,68.736373,1588.935581,4.763566,4.0,1,7569,9.327379,58.0,14.129857,1.000000
4,5,B,22.0,43.487165,65.487165,-21.487165,956.717624,0.505896,0.0,0,484,4.690416,58.0,14.129857,0.000000
5,6,B,34.0,NaN,54.447206,13.552794,695.204988,1.662819,1.0,0,1156,5.830952,58.0,14.129857,0.184615
6,7,B,81.0,32.539204,113.539204,48.460796,2635.675503,2.489305,2.0,1,6561,9.000000,58.0,14.129857,0.907692
7,8,B,41.0,2.002212,43.002212,38.997788,82.090706,20.477349,20.0,1,1681,6.403124,58.0,14.129857,0.292308
8,9,B,82.0,40.596143,122.596143,41.403857,3328.883694,2.019896,2.0,0,6724,9.055385,58.0,14.129857,0.923077
9,10,C,61.0,22.051052,83.051052,38.948948,1345.114160,2.766308,2.0,1,3721,7.810250,58.0,14.129857,0.600000